### ISSUE TITLE
How to translate time values stored in stv_blocklist to readable format

### ISSUE THREAD

**Issue by sbansal6** [JefClaes/amazon-redshift-fundamentals#5]
First of all thanks for your work. Its very helpful.
In your notes you mentioned "**After translating the min and max value, the result set looks something like this.**"

As per stv_blocklist documentation, min and max column stores Stores first eight characters as 64-bit integer for non-numeric data, how are you able to translate them back into readable dates in your example:-

block | min | max
-- | -- | --
0 | 2014-1-1 | 2014-2-3
1 | 2014-2-3 | 2014-3-8

**Comment by JefClaes** [comment]
You can't when there's data loss. When would you translate them back?
